### ISSUE TITLE
Can't stop room countdown

### ISSUE THREAD

**Issue by Ochii** [Ochii/cso2-master-server#13]
If you cancel the game start counter, the server will crash.

Error: Data buffer is too small
    at InRoomPacket.readUInt8 (C:\Users\admin\dist\packets\in\packet.js:88:19)
    at new InRoomCountdown (C:\Users\admin\dist\packets\in\room\countdown.js:10:31)
    at InRoomPacket.parse (C:\Users\admin\dist\packets\in\room.js:89:34)
    at new InPacketBase (C:\Users\admin\dist\packets\in\packet.js:21:14)
    at new InRoomPacket (C:\Users\admin\dist\packets\in\room.js:23:1)
    at ChannelManager.onRoomRequest (C:\Users\admin\dist\channel\channelmanager.js:74:27)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:186:38)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)

_Originally posted by @DebugBios in https://github.com/Ochii/cso2-master-server/issues/6#issuecomment-446765959_

**Comment by Ochii** [comment]
@DebugBios can you try the [latest release](https://github.com/Ochii/cso2-master-server/releases/tag/20181214183817-acf0306)?

**Comment by DebugBios** [comment]
Errors still occur.

Error: Data buffer is too small
    at InRoomPacket.readUInt8 (C:\Users\admin\dist\packets\in\packet.js:94:19)
    at new InRoomCountdown (C:\Users\admin\dist\packets\in\room\countdown.js:10:31)
    at InRoomPacket.parse (C:\Users\admin\dist\packets\in\room.js:89:34)
    at new InPacketBase (C:\Users\admin\dist\packets\in\packet.js:21:14)
    at new InRoomPacket (C:\Users\admin\dist\packets\in\room.js:23:1)
    at ChannelManager.onRoomRequest (C:\Users\admin\dist\channel\channelmanager.js:46:27)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:189:38)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)

**Comment by Ochii** [comment]
Sorry, I have sent you the wrong release. [This is the correct one](https://github.com/Ochii/cso2-master-server/releases/tag/20181215004230-cad8646)

**Comment by DebugBios** [comment]
It works properly. Thank you.
