### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#20]
If there are more than two people in the room in the latest version,

When the game starts, the server starts to crash.

Error: Room: host's countdown does not match ours
    at Room.progressCountdown (C:\Users\admin\dist\room\room.js:323:19)
    at ChannelManager.onGameStartToggleRequest (C:\Users\admin\dist\channel\channelmanager.js:340:29)
    at ChannelManager.onRoomRequest (C:\Users\admin\dist\channel\channelmanager.js:70:25)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:200:38)
    at ServerInstance.processPackets (C:\Users\admin\dist\serverinstance.js:169:18)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

**Comment by DebugBios** [comment]
C:\Users\rat96>npm run start -- --ip-address [my router external IP address]

> cso2-master-server@0.3.0 start C:\Users\rat96
> node dist/server.js "--ip-address" "[my router external IP address]"

server error: bind EADDRNOTAVAIL [my router external IP address]:30002
C:\Users\rat96\dist\serverinstance.js:112
        throw err;
        ^

Error: bind EADDRNOTAVAIL [my router external IP address]:30002
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by DebugBios** [comment]
server log

Your environment has been set up for using Node.js 8.11.4 (x64) and npm.

C:\Users\rat96>npm run start -- --ip-address

> cso2-master-server@0.3.0 start C:\Users\rat96
> node dist/server.js "--ip-address"

Using interface Wi-Fi (192.168.0.2)
holepunch listening at 192.168.0.2:30002
server is now started listening at 192.168.0.2:30001
new client connected 192.168.0.2:7368 uuid: 9e969318-bfcb-4acc-b978-79f07a4bb8ac
9e969318-bfcb-4acc-b978-79f07a4bb8ac sent a version packet. clientHash: 611e84b30de268f09e5973d2db3884ac
user TEST01 logged in, uuid: 9e969318-bfcb-4acc-b978-79f07a4bb8ac
unknown packet id 72 from 9e969318-bfcb-4acc-b978-79f07a4bb8ac
unknown packet id 91 from 9e969318-bfcb-4acc-b978-79f07a4bb8ac
user "TEST01" requested server list, sending...
user "TEST01" requested room list successfully, sending...
unknown packet id 107 from 9e969318-bfcb-4acc-b978-79f07a4bb8ac
user "TEST01" requested a new room. room name: "명작의 부활! 카운터스트라이크 온라인2" room id: 1
host "TEST01" updated room "명작의 부활! 카운터스트라이크 온라인2"'s settings (id: 1)
host "TEST01" updated room "명작의 부활! 카운터스트라이크 온라인2"'s settings (id: 1)
host "TEST01" updated room "명작의 부활! 카운터스트라이크 온라인2"'s settings (id: 1)
host "TEST01" updated room "명작의 부활! 카운터스트라이크 온라인2"'s settings (id: 1)
new client connected 192.168.0.2:7385 uuid: e76e7640-c403-4c90-b84a-ad922f567efe
e76e7640-c403-4c90-b84a-ad922f567efe sent a version packet. clientHash: 611e84b30de268f09e5973d2db3884ac
user TEST02 logged in, uuid: e76e7640-c403-4c90-b84a-ad922f567efe
unknown packet id 72 from e76e7640-c403-4c90-b84a-ad922f567efe
unknown packet id 91 from e76e7640-c403-4c90-b84a-ad922f567efe
user "TEST02" requested server list, sending...
user "TEST02" requested room list successfully, sending...
unknown packet id 107 from e76e7640-c403-4c90-b84a-ad922f567efe
user "TEST02" joined a new room. room name: "명작의 부활! 카운터스트라이크 온라인2" room id: 1
user "TEST02" tried to update a room's settings, although it isn't the host.room name "명작의 부활! 카운터스트라이크 온 라인2" room id: 1
user "TEST02" readied in room "명작의 부활! 카운터스트라이크 온라인2" (id 1)
user "TEST01" tried to toggle a room's game start countdown, although it can't start. room name "명작의 부활! 카운터스트라이크 온라인2" room id: 1
user "TEST02" unreadied in room "명작의 부활! 카운터스트라이크 온라인2" (id 1)
room "명작의 부활! 카운터스트라이크 온라인2"'s (id 1) countdown is at 6
C:\Users\rat96\dist\room\room.js:323
            throw new Error('Room: host\'s countdown does not match ours');
            ^

Error: Room: host's countdown does not match ours
    at Room.progressCountdown (C:\Users\rat96\dist\room\room.js:323:19)
    at ChannelManager.onGameStartToggleRequest (C:\Users\rat96\dist\channel\channelmanager.js:473:29)
    at ChannelManager.onRoomRequest (C:\Users\rat96\dist\channel\channelmanager.js:73:25)
    at ServerInstance.onIncomingPacket (C:\Users\rat96\dist\serverinstance.js:198:38)
    at ServerInstance.processPackets (C:\Users\rat96\dist\serverinstance.js:169:18)
    at ServerInstance.onSocketData (C:\Users\rat96\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\rat96\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cso2-master-server@0.3.0 start: `node dist/server.js "--ip-address"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cso2-master-server@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rat96\AppData\Roaming\npm-cache\_logs\2019-01-06T18_01_03_782Z-debug.log

**Comment by Ochii** [comment]
Try the [latest release](https://github.com/Ochii/cso2-master-server/releases/tag/20190106202141-41a3e80) and reply if it works now

**Comment by DebugBios** [comment]
It works, but if the person entering the room is not prepared, the room counter will not start.
