### ISSUE TITLE
when I got in game assault map, I can't choose any team,and when I decide to go to the main menu, game crash, and cmd tell me this

### ISSUE THREAD

**Issue by njxxwhx** [Ochii/cso2-master-server#3]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cso2-master-server@0.1.0 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cso2-master-server@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\njxxwhx\AppData\Roaming\npm-cache\_logs\2018-09-22T12_32_19_583Z-debug.log

**Comment by Ochii** [comment]
Can you send the text printed before that? The error should be there

**Comment by loonbg** [comment]
I got this error 

TypeError: Cannot read property 'userId' of null
    at room.users.forEach (C:\Users\MiRo\Desktop\cso2-master-server-master\dist\events\room.js:40:45)
    at Array.forEach (<anonymous>)
    at OnRoomPacket.buildOutPacket (C:\Users\MiRo\Desktop\cso2-master-server-master\dist\events\room.js:39:24)
    at OnRoomPacket.onCallback (C:\Users\MiRo\Desktop\cso2-master-server-master\dist\events\base.js:21:21)
    at Function.handlePacket (C:\Users\MiRo\Desktop\cso2-master-server-master\dist\packetevents.js:42:30)
    at Function.onSocketData (C:\Users\MiRo\Desktop\cso2-master-server-master\dist\servermanager.js:100:50)
    at Socket.newSocket.on (C:\Users\MiRo\Desktop\cso2-master-server-master\dist\servermanager.js:76:27)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
