### ISSUE TITLE
Server crashes while create a new room

### ISSUE THREAD

**Issue by GEEKiDoS** [Ochii/cso2-master-server#6]
```
packet from c9e5ea62-9f96-4d80-bf4f-a3f71d13d470 seq: 8 length: 48
C:\Users\Administrator\cso2-master-server\dist\packets\in\packet.js:112
            throw new Error('Data buffer is too small');
            ^

Error: Data buffer is too small
    at InRoomPacket.readUInt32 (C:\Users\Administrator\cso2-master-server\dist\p
ackets\in\packet.js:112:19)
    at new InRoomNewRequest (C:\Users\Administrator\cso2-master-server\dist\pack
ets\in\room\fullrequest.js:25:31)
    at InRoomPacket.parse (C:\Users\Administrator\cso2-master-server\dist\packet
s\in\room.js:74:35)
    at new InPacketBase (C:\Users\Administrator\cso2-master-server\dist\packets\
in\packet.js:21:14)
    at new InRoomPacket (C:\Users\Administrator\cso2-master-server\dist\packets\
in\room.js:23:1)
    at ChannelManager.onRoomRequest (C:\Users\Administrator\cso2-master-server\d
ist\channel\channelmanager.js:74:27)
    at ServerInstance.onIncomingPacket (C:\Users\Administrator\cso2-master-serve
r\dist\serverinstance.js:186:38)
    at ServerInstance.onSocketData (C:\Users\Administrator\cso2-master-server\di
st\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\Administrator\cso2-master-server\dist\serve
rinstance.js:85:18)
    at Socket.emit (events.js:182:13)
```

**Comment by GEEKiDoS** [comment]
But it worked sometimes....

**Comment by Ochii** [comment]
Can you tell me the steps you took to crash the server?

**Comment by GEEKiDoS** [comment]
> Can you tell me the steps you took to crash the server?

First I start server with ```npm run-script start -- -i 0.0.0.0```
Then start client with ``` .\launcher.exe -lang schinese -masterip 119.29.251.91 -masterport 30001```
after that, I just followed 

> Getting ingame

Section in the README.md of client repo,
after 

> Create your own room by pressing 방만들기 (room) (example) then choosing game mode (example);

the server crashes with "Data buffer is too small"

**Comment by GEEKiDoS** [comment]
![qq 20181118122459](https://user-images.githubusercontent.com/14933408/48668618-fa95a680-eb2c-11e8-9573-bd01c31aefe2.jpg)
It worked sometimes,  IDK what's wrong

**Comment by Ochii** [comment]
which game mode did you select?

**Comment by Ochii** [comment]
can you test with the [latest launcher](https://github.com/Ochii/cso2-launcher/releases/tag/Build-0.1.9) and the [latest master-server](https://github.com/Ochii/cso2-master-server/releases/tag/20181209035514-8245e4a)?

**Comment by DebugBios** [comment]
An error occurs when creating a room with LAN IP in the latest version.

Error: Data buffer is too small
    at InRoomPacket.readUInt32 (C:\Users\admin\dist\packets\in\packet.js:112:19)
    at new InRoomNewRequest (C:\Users\admin\dist\packets\in\room\fullrequest.js:25:31)
    at InRoomPacket.parse (C:\Users\admin\dist\packets\in\room.js:74:35)
    at new InPacketBase (C:\Users\admin\dist\packets\in\packet.js:21:14)
    at new InRoomPacket (C:\Users\admin\dist\packets\in\room.js:23:1)
    at ChannelManager.onRoomRequest (C:\Users\admin\dist\channel\channelmanager.js:74:27)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:186:38)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)

**Comment by DebugBios** [comment]
If you cancel the game start counter, the server will crash.

Error: Data buffer is too small
    at InRoomPacket.readUInt8 (C:\Users\admin\dist\packets\in\packet.js:88:19)
    at new InRoomCountdown (C:\Users\admin\dist\packets\in\room\countdown.js:10:31)
    at InRoomPacket.parse (C:\Users\admin\dist\packets\in\room.js:89:34)
    at new InPacketBase (C:\Users\admin\dist\packets\in\packet.js:21:14)
    at new InRoomPacket (C:\Users\admin\dist\packets\in\room.js:23:1)
    at ChannelManager.onRoomRequest (C:\Users\admin\dist\channel\channelmanager.js:74:27)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:186:38)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)

**Comment by Ochii** [comment]
@GEEKiDoS I couldn't replicate this on a virtual machine running windows 7 with korean system locale. Is this still happening to you?

**Comment by ChenyuHou** [comment]
Hello,I can answer you about this question, The master-sever can not know Chinese room name .Please use English or Korean room name.

**Comment by Ochii** [comment]
@GEEKiDoS @ChenyuHou can any of you log the packets with the cmd argument `--log-packets`, then upload them somewhere? You can email them to me, if you don't wish to make the packets public

**Comment by CarldricGaming** [comment]
[packets.zip](https://github.com/Ochii/cso2-master-server/files/2718145/packets.zip)
here is the packets file.

Take note this:

> The Solution Problem is the server.dll from CSO2\Bin that unavailable with other cvar command. It say they need to set about the most important that command is this "sv_cheats 1" for multiplayer.

**Comment by CarldricGaming** [comment]
![bandicam 2018-12-31 18-04-36-717](https://user-images.githubusercontent.com/46277745/50558157-a59da080-0d26-11e9-9dc5-f256f79d3baa.jpg)

**Comment by Ochii** [comment]
Does [launcher's build 0.1.11](https://github.com/Ochii/cso2-launcher/releases/tag/Build-0.1.11) fix this?

**Comment by CarldricGaming** [comment]
My Specs:
`CPU: AMD Athlon 64 x2 Dual Core Processor +5000
RAM: 2GB
GPU: NVIDIA Geforce GT 630
OS: Windows 10 Pro x64`

**Comment by Ochii** [comment]
@CarldricGaming Those messages are not an issue, they come from CS:S I think

Also, please create a new issue if your problem isn't related to any existing one's

**Comment by Ochii** [comment]
Considering @DebugBios managed to create a room (see #19 or #20), I'll assume this is fixed
