### ISSUE TITLE
error occurs when login

### ISSUE THREAD

**Issue by kjm1922** [Ochii/cso2-master-server#7]
node.js has an error, but I can access the game.
However, the server is not visible.

> node.js command prompt
```
E:\Nexon\Counter-Strike Online 2\Server>npm run start -- --ip-address 192.168.0.81

> cso2-master-server@0.2.0 start E:\Nexon\Counter-Strike Online 2\Server
> node dist/server.js "--ip-address" "192.168.0.81"

holepunch listening at 192.168.0.81:30002
server is now started listening at 192.168.0.81:30001
new client connected 192.168.0.81:10944 uuid: 547b0f37-4a6a-4969-96e5-ae4a855c34f4
packet from 547b0f37-4a6a-4969-96e5-ae4a855c34f4 seq: 1 length: 37
E:\Nexon\Counter-Strike Online 2\Server\dist\packets\packetstring.js:14
        const expectedLen = new TextEncoder().encode(str).length;
                            ^

ReferenceError: TextEncoder is not defined
    at new PacketString (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\packetstring.js:14:29)
    at Function.from (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\packetstring.js:11:16)
    at InVersionPacket.readString (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\packet.js:144:49)
    at InVersionPacket.parse (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\version.js:21:32)
    at new InPacketBase (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\packet.js:21:14)
    at new InVersionPacket (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\version.js:13:1)
    at UserManager.onVersionPacket (E:\Nexon\Counter-Strike Online 2\Server\dist\user\usermanager.js:70:31)
    at ServerInstance.onIncomingPacket (E:\Nexon\Counter-Strike Online 2\Server\dist\serverinstance.js:178:35)
    at ServerInstance.onSocketData (E:\Nexon\Counter-Strike Online 2\Server\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (E:\Nexon\Counter-Strike Online 2\Server\dist\serverinstance.js:85:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cso2-master-server@0.2.0 start: `node dist/server.js "--ip-address" "192.168.0.81"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cso2-master-server@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wjdfl\AppData\Roaming\npm-cache\_logs\2018-12-04T08_26_42_146Z-debug.log
```

> debug log
```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--ip-address',
1 verbose cli   '192.168.0.81' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cso2-master-server@0.2.0~prestart: cso2-master-server@0.2.0
6 info lifecycle cso2-master-server@0.2.0~start: cso2-master-server@0.2.0
7 verbose lifecycle cso2-master-server@0.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle cso2-master-server@0.2.0~start: PATH: E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Nexon\Counter-Strike Online 2\Server\node_modules\.bin;C:\Users\wjdfl\AppData\Roaming\npm;E:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\Program Files (x86)\UltraEdit;C:\WINDOWS\System32\OpenSSH\;E:\Program Files\nodejs\;C:\Users\wjdfl\AppData\Local\Microsoft\WindowsApps;C:\Users\wjdfl\AppData\Local\Programs\Fiddler;C:\Users\wjdfl\AppData\Local\GitHubDesktop\bin;C:\Users\wjdfl\AppData\Local\Microsoft\WindowsApps;C:\Users\wjdfl\AppData\Roaming\npm
9 verbose lifecycle cso2-master-server@0.2.0~start: CWD: E:\Nexon\Counter-Strike Online 2\Server
10 silly lifecycle cso2-master-server@0.2.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'node dist/server.js "--ip-address" "192.168.0.81"' ]
11 silly lifecycle cso2-master-server@0.2.0~start: Returned: code: 1  signal: null
12 info lifecycle cso2-master-server@0.2.0~start: Failed to exec start script
13 verbose stack Error: cso2-master-server@0.2.0 start: `node dist/server.js "--ip-address" "192.168.0.81"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cso2-master-server@0.2.0
15 verbose cwd E:\Nexon\Counter-Strike Online 2\Server
16 verbose Windows_NT 10.0.17134
17 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start" "--" "--ip-address" "192.168.0.81"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error cso2-master-server@0.2.0 start: `node dist/server.js "--ip-address" "192.168.0.81"`
22 error Exit status 1
23 error Failed at the cso2-master-server@0.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kjm1922** [comment]
I updated  the version of node js, but still same error occurred.

```
E:\Nexon\Counter-Strike Online 2\Server>node -v
v10.14.1

E:\Nexon\Counter-Strike Online 2\Server>npm -v
6.4.1
```

**Comment by Ochii** [comment]
Try the latest commit
