### ISSUE TITLE
If select any game mode, server crashed

### ISSUE THREAD

**Issue by kjm1922** [Ochii/cso2-master-server#8]
If attempt to create room by select any game mode, server will crashed.

> npm log
```
E:\Nexon\Counter-Strike Online 2\Server>npm run start

> cso2-master-server@0.2.0 start E:\Nexon\Counter-Strike Online 2\Server
> node dist/server.js

Using interface 이더넷 (192.168.0.81)
holepunch listening at 192.168.0.81:30002
server is now started listening at 192.168.0.81:30001
new client connected 192.168.0.81:4635 uuid: a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9
packet from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 seq: 1 length: 37
a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 sent a version packet. clientHash: 611e84b30de268f09e5973d2db3884ac
(node:4256) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
packet from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 seq: 2 length: 61
trying to login as kjm1922
packet from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 seq: 3 length: 2
unknown packet id 72 from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9
packet from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 seq: 4 length: 3
unknown packet id 91 from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9
packet from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 seq: 5 length: 1
packet from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 seq: 6 length: 3
packet from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 seq: 7 length: 2
unknown packet id 107 from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9
packet from a3f81d13-2a57-4a4d-8a98-c88bfd2dd9d9 seq: 8 length: 56
E:\Nexon\Counter-Strike Online 2\Server\dist\packets\packetstring.js:19
                throw new Error('The string\'s expected length is different from the one in the packet');
                ^

Error: The string's expected length is different from the one in the packet
    at new PacketString (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\packetstring.js:19:23)
    at Function.from (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\packetstring.js:12:16)
    at InRoomPacket.readString (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\packet.js:144:49)
    at new InRoomNewRequest (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\room\fullrequest.js:9:34)
    at InRoomPacket.parse (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\room.js:74:35)
    at new InPacketBase (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\packet.js:21:14)
    at new InRoomPacket (E:\Nexon\Counter-Strike Online 2\Server\dist\packets\in\room.js:23:1)
    at ChannelManager.onRoomRequest (E:\Nexon\Counter-Strike Online 2\Server\dist\channel\channelmanager.js:74:27)
    at ServerInstance.onIncomingPacket (E:\Nexon\Counter-Strike Online 2\Server\dist\serverinstance.js:186:38)
    at ServerInstance.onSocketData (E:\Nexon\Counter-Strike Online 2\Server\dist\serverinstance.js:160:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cso2-master-server@0.2.0 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cso2-master-server@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wjdfl\AppData\Roaming\npm-cache\_logs\2018-12-06T08_39_39_939Z-debug.log
```

>debug log
```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cso2-master-server@0.2.0~prestart: cso2-master-server@0.2.0
6 info lifecycle cso2-master-server@0.2.0~start: cso2-master-server@0.2.0
7 verbose lifecycle cso2-master-server@0.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle cso2-master-server@0.2.0~start: PATH: E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\Nexon\Counter-Strike Online 2\Server\node_modules\.bin;C:\Users\wjdfl\AppData\Roaming\npm;E:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\Program Files (x86)\UltraEdit;C:\WINDOWS\System32\OpenSSH\;E:\Program Files\nodejs\;C:\Users\wjdfl\AppData\Local\Microsoft\WindowsApps;C:\Users\wjdfl\AppData\Local\Programs\Fiddler;C:\Users\wjdfl\AppData\Local\GitHubDesktop\bin;C:\Users\wjdfl\AppData\Local\Microsoft\WindowsApps;C:\Users\wjdfl\AppData\Roaming\npm
9 verbose lifecycle cso2-master-server@0.2.0~start: CWD: E:\Nexon\Counter-Strike Online 2\Server
10 silly lifecycle cso2-master-server@0.2.0~start: Args: [ '/d /s /c', 'node dist/server.js' ]
11 silly lifecycle cso2-master-server@0.2.0~start: Returned: code: 1  signal: null
12 info lifecycle cso2-master-server@0.2.0~start: Failed to exec start script
13 verbose stack Error: cso2-master-server@0.2.0 start: `node dist/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid cso2-master-server@0.2.0
15 verbose cwd E:\Nexon\Counter-Strike Online 2\Server
16 verbose Windows_NT 10.0.17134
17 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v10.14.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error cso2-master-server@0.2.0 start: `node dist/server.js`
22 error Exit status 1
23 error Failed at the cso2-master-server@0.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Ochii** [comment]
Can you try again with [this launcher](https://github.com/Ochii/cso2-launcher/releases/tag/Build-0.1.8)?

I couldn't reproduce it in a docker instance with node v10.14.1

**Comment by kjm1922** [comment]
it works! thank you
