### ISSUE TITLE
Unable to change team

### ISSUE THREAD

**Issue by Ochii** [Ochii/cso2-master-server#9]
Unable to change the team, the person entering the room cannot see the bot, and when the game starts, each person gets up with a crash.

```
Error: This is not a packet
    at InPacketBase.parse (C:\Users\admin\dist\packets\in\packet.js:181:19)
    at new InPacketBase (C:\Users\admin\dist\packets\in\packet.js:21:14)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:169:24)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
```

_Originally posted by @DebugBios in https://github.com/Ochii/cso2-master-server/issues/5#issuecomment-445519382_

**Comment by DebugBios** [comment]
![default](https://user-images.githubusercontent.com/44349391/49767695-e2c0d500-fd1c-11e8-8db6-9ce4bf50d861.PNG)
People entering cannot click on the preparation and enter. Also, if you use Bot mode, you will have an unusually large number of bots.

**Comment by DebugBios** [comment]
![launcher 2018 12 11 - 15 49 55 01 mp4_20181211_155420 940](https://user-images.githubusercontent.com/44349391/49783525-6a2e3880-fd5d-11e8-8f7d-6b3db1666d12.jpg)
Starting with a certain probability, the entry person cannot use the console, and after about 30 seconds the server will crash and cause serious errors in the entrant's OS.


TypeError: Cannot read property 'split' of undefined
    at Object.ip.toLong (C:\Users\admin\node_modules\ip\lib\ip.js:404:6)
    at UserManager.onUdpPacket (C:\Users\admin\dist\user\usermanager.js:66:30)
    at ServerInstance.onIncomingPacket (C:\Users\admin\dist\serverinstance.js:188:35)
    at ServerInstance.onSocketData (C:\Users\admin\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\admin\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)

**Comment by DebugBios** [comment]
If you use the latest version, you can exchange teams, but you still have to use the jointeam console when entering the game.

**Comment by DebugBios** [comment]
https://youtu.be/Jdue8Aqeq7I
